export const routes = {
    entries: '/v1/entries',
    privateEntries: '/private/entries',
    favorites: '/v1/favorites',
    states: '/v1/states',
    locks: '/v1/locks',
    privateCreateLock: (entryId: string) => `/private/locks/${entryId}`,
    collections: '/v1/collections',
    deleteCollections: '/v1/delete-collections',
    deleteWorkbooks: '/v2/delete-workbooks',
    getCollectionsListByIds: '/v1/collections-get-list-by-ids',
    getWorkbooksListByIds: '/v2/workbooks-get-list-by-ids',
    moveCollections: '/v1/move-collections',
    moveWorkbooks: '/v2/move-workbooks',
    privateCollections: '/private/v1/collections',
    collectionContent: '/v1/collection-content',
    structureItems: '/v1/structure-items',
    rootCollectionPermissions: '/v1/root-collection-permissions',
    workbooks: '/v2/workbooks',
    privateWorkbooks: '/private/v2/workbooks',
    getEntriesData: '/v1/get-entries-data',
    getEntriesAnnotation: '/v1/get-entries-annotation',
    getEntriesMeta: '/v1/get-entries-meta',
    getEntryMetaRoute: (entryId: string) => `/v1/entries/${entryId}/meta`,
    getPrivateEntryMetaRoute: (entryId: string) => `/private/entries/${entryId}/meta`,
    checkEntriesExistence: '/v1/check-entries-existence',
    setDefaultColorPalette: '/v1/tenants/set-default-color-palette',
    updateTenantSettings: '/v1/tenants/settings',
    colorPalettes: '/v1/color-palettes',
    getEntriesRelations: '/v1/get-entries-relations',
    privateGetEntriesRelations: '/private/v1/get-entries-relations',
    privateUpdateEntryUnversionedData: (entryId: string) =>
        `/private/entries/${entryId}/unversioned-data`,
    allWorkbooks: '/private/all-workbooks',
    entryRevisions: (entryId: string) => `/v1/entries/${entryId}/revisions`,
    entryRelations: (entryId: string) => `/v1/entries/${entryId}/relations`,
    switchRevision: (entryId: string) => `/private/entries/${entryId}/switch-revision`,
} as const;
