export const selectedEntryColumns = [
    'scope',
    'type',
    'key',
    'innerMeta',
    'createdBy',
    'createdAt',
    'updatedAt',
    'updatedBy',
    'isDeleted',
    'deletedAt',
    'hidden',
    'displayKey',
    'entryId',
    'savedId',
    'publishedId',
    'tenantId',
    'name',
    'sortName',
    'public',
    'unversionedData',
    'workbookId',
] as const;
