import {Entry} from '../../../../db/models/new/entry';

export const formatEntryModel = (entryModel: Entry) => {
    return {
        entryId: entryModel.entryId,
        scope: entryModel.scope,
        type: entryModel.type,
        key: entryModel.displayKey,
        createdBy: entryModel.createdBy,
        createdAt: entryModel.createdAt,
        updatedBy: entryModel.updatedBy,
        updatedAt: entryModel.updatedAt,
        savedId: entryModel.savedId,
        publishedId: entryModel.publishedId,
        tenantId: entryModel.tenantId,
        workbookId: entryModel.workbookId,
        innerMeta: entryModel.innerMeta,
        hidden: entryModel.hidden,
        displayKey: entryModel.displayKey,
        name: entryModel.name,
        sortName: entryModel.sortName,
        public: entryModel.public,
    };
};

// Scope: 'scope',
//     Type: 'type',
//     Key: 'key',
//     InnerMeta: 'innerMeta',
//     CreatedBy: 'createdBy',
//     CreatedAt: 'createdAt',
//     UpdatedBy: 'updatedBy',
//     UpdatedAt: 'updatedAt',
//     IsDeleted: 'isDeleted',
//     DeletedAt: 'deletedAt',
//     Hidden: 'hidden',
//     DisplayKey: 'displayKey',
//     EntryId: 'entryId',
//     SavedId: 'savedId',
//     PublishedId: 'publishedId',
//     TenantId: 'tenantId',
//     Name: 'name',
//     SortName: 'sortName',
//     Public: 'public',
//     UnversionedData: 'unversionedData',
//     WorkbookId: 'workbookId',
//     Mirrored: 'mirrored',
//     Branding: 'branding',
